### ISSUE TITLE
config backend Supabase and database sample 

### ISSUE THREAD

**Issue by vinagroup** [fernandohos/fasthome#1]
Please note document for config backend Supabase and database sample.

Thanks

**Comment by fernandohos** [comment]
Hi,
can you be more specific?
maybe using the issue template.

**Comment by fernandohos** [comment]
Hi @vinagroup ,
can you be more specific?
maybe using the issue template.

**Comment by vinagroup** [comment]
I think need sample Supabase database nosql and tutorial config firebase.

Thanks

**Comment by vinagroup** [comment]
Hi Fernando

How to build template database with? sakeohyxietmvdzfvzjq.supabase.co
Do you share your database template?

Thanks

Vào Th 7, 2 thg 7, 2022 vào lúc 07:20 Fernando Henrique <
***@***.***> đã viết:

**Comment by fernandohos** [comment]
You can find the script to create the houses table template [here](https://github.com/fernandohos/fasthome/blob/main/db/houses.sql).
